### ISSUE TITLE
Implement Alt-Click like in GitHub

### ISSUE THREAD

**Issue by piRGoif** [Molkobain/itop-caselogs-toggler#2]
In GitHub, inside a pull request, all changes can be collapsed / open using Alt + Click
See https://help.github.com/articles/using-keyboard-shortcuts/#changes-in-pull-requests

Would be very nice to implement the same 8)

**Comment by piRGoif** [comment]
The event.altKey attribute is the way to do !
See :
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/altKey
http://api.jquery.com/category/events/event-object/

**Comment by piRGoif** [comment]
A small demo :
https://codepen.io/pgoiffon/pen/xMYOxW

**Comment by Molkobain** [comment]
What's the excepted behavior?
* Alt + Click anywhere on the page
* Alt + Click on an entry

**Comment by piRGoif** [comment]
On an entry :)

**Comment by Molkobain** [comment]
Done! Thanks for the idea @piRGoif :)
