### ISSUE TITLE
Handle ticket modification

### ISSUE THREAD

**Issue by piRGoif** [Molkobain/itop-caselogs-toggler#3]
When switching to modification, the toggler isn't available anymore.
Saving the open/close state between display and edit would be nice too O:)

**Comment by Molkobain** [comment]
Hello @piRGoif ,

Actually this is a bug! Togglers should be there in edition... It's working in the portal but not in the console because its has major markup changes between view / edit modes. I'll look into it. Thanks!

**Comment by Molkobain** [comment]
Fixed in cb49053, thanks again! :)
